config/routes.rb
Sanbaoyuan::Application.routes.draw do
  resources :newsposts

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/newspost.rb
class Newspost < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/newsposts_controller.rb
class NewspostsController < ApplicationController
  # GET /newsposts
  # GET /newsposts.json
  def index
    @newsposts = Newspost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsposts }
    end
  end

  # GET /newsposts/1
  # GET /newsposts/1.json
  def show
    @newspost = Newspost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newspost }
    end
  end

  # GET /newsposts/new
  # GET /newsposts/new.json
  def new
    @newspost = Newspost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newspost }
    end
  end

  # GET /newsposts/1/edit
  def edit
    @newspost = Newspost.find(params[:id])
  end

  # POST /newsposts
  # POST /newsposts.json
  def create
    @newspost = Newspost.new(params[:newspost])

    respond_to do |format|
      if @newspost.save
        format.html { redirect_to @newspost, notice: 'Newspost was successfully created.' }
        format.json { render json: @newspost, status: :created, location: @newspost }
      else
        format.html { render action: "new" }
        format.json { render json: @newspost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsposts/1
  # PUT /newsposts/1.json
  def update
    @newspost = Newspost.find(params[:id])

    respond_to do |format|
      if @newspost.update_attributes(params[:newspost])
        format.html { redirect_to @newspost, notice: 'Newspost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newspost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsposts/1
  # DELETE /newsposts/1.json
  def destroy
    @newspost = Newspost.find(params[:id])
    @newspost.destroy

    respond_to do |format|
      format.html { redirect_to newsposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsposts_helper.rb
module NewspostsHelper
end

app/views/contact/index.html.erb
<div class="content_position">
    <p>您现在的位置：<%= link_to "首页" %> > <%= link_to "联系方式" %> </p>
</div>

<div class="content_list">
    <div class="content_title">
        <p>联系方式</p>
    </div>

    <table>
        <tr>
            <td>联系人：</td>
            <td>潘峰</td>
        </tr>
        <tr>
            <td>电话：</td>
            <td>0432-64822789</td>
        </tr>
        <tr>
            <td>移动电话：</td>
            <td>13264203335</td>
        </tr>
        <tr>
            <td>地址：</td>
            <td>中国 吉林 吉林市船营区 欢喜新林路9号三宝元保健酒厂</td>
        </tr>
        <tr>
            <td>邮编：</td>
            <td>132011</td>
        </tr>
    </table>

    <br />

</div>

<div class="content_navi">
    <p>
    <%= link_to "首页", { :controller => "home", :action => "index"} %> </br>
    <%= link_to "企业概况" %> </br>
    <%= link_to "新闻中心" %> </br>
    <%= link_to "产品介绍" %> </br>
    <%= link_to "合作伙伴" %> </br>
    <%= link_to "联系方式", { :controller => "contact", :action => "index"} %> </br>
    </p>
</div>

app/views/home/index.html.erb
<div class="content_position">
    <p>您现在的位置：<%= link_to "首页" %> </p>
</div>

<div class="content_list">
</div>

<div class="content_navi">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>吉林市三宝元保健酒厂</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="logobar">
        <div class="logobar_inner">
            <div class="container logobar_container">
                <%= link_to "三宝元", { :controller => "home", :action => "index"} %>
            </div>
        </div>
    </div>
    
    <div class="navibar">
        <div class="container">
            <span class="navibar_container">
                <%= link_to "首页", { :controller => "home", :action => "index"} %>
            </span>
            <span class="navibar_container">
                <%= link_to "企业概况" %>
            </span>
            <span class="navibar_container">
                <%= link_to "新闻中心", { :controller => "newsposts", :action => "index"} %>
            </span>
            <span class="navibar_container">
                <%= link_to "产品介绍" %>
            </span>
            <span class="navibar_container">
                <%= link_to "合作伙伴" %>
            </span>
            <span class="navibar_container">
                <%= link_to "联系方式", { :controller => "contact", :action => "index"} %>
            </span>
            
            <p> <%= image_tag "/assets/logo2.png" %> </p>
        </div>
    </div>

    <div class="real_content">
        <div class="container">

            <%= yield %>

        </div>
    </div>
        
    <div class="footer">
        <div class="container">
            <p align="center">中国吉林省吉林市欢喜新林路9号 三宝元保健酒厂</p>
            <p align="center">
            Copyright © 2012 Sanbaoyuan
            <script src="http://s22.cnzz.com/stat.php?id=4542871&web_id=4542871&show=pic" language="JavaScript"></script>
            </p>
        </div>
    </div>
</body>
</html>

app/views/newsposts/_form.html.erb
<%= form_for(@newspost) do |f| %>
  <% if @newspost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newspost.errors.count, "error") %> prohibited this newspost from being saved:</h2>

      <ul>
      <% @newspost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsposts/edit.html.erb
<h1>Editing newspost</h1>

<%= render 'form' %>

<%= link_to 'Show', @newspost %> |
<%= link_to 'Back', newsposts_path %>

app/views/newsposts/index.html.erb
<div class="content_position">
    <p>您现在的位置：<%= link_to "首页" %> > <%= link_to "新闻中心" %> </p>
</div>

<div class="content_list">
    <div class="content_title">
        <p>新闻中心</p>
    </div>
    
    <table>
    <% @newsposts.each do |newspost| %>
      <tr>
        <td><%= newspost.title %></td>
        <td><%= newspost.content %></td>
        <td><%= link_to '阅读', newspost %></td>
        <td><%= link_to '编辑', edit_newspost_path(newspost) %></td>
        <td><%= link_to '删除', newspost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
    
    <br />
    
</div>

<div class="content_navi">
    <%= link_to '发布新闻', new_newspost_path %>
</div>

app/views/newsposts/new.html.erb
<h1>New newspost</h1>

<%= render 'form' %>

<%= link_to 'Back', newsposts_path %>

app/views/newsposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @newspost.title %>
</p>

<p>
  <b>Content:</b>
  <%= @newspost.content %>
</p>


<%= link_to 'Edit', edit_newspost_path(@newspost) %> |
<%= link_to 'Back', newsposts_path %>